#!/usr/bin/bash

# notification daemon
dunst

# waybar
waybar

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

hyprpaper
